Settings
oblazej/nauka pull request #2
Opened 2021-04-23 15:45 UTC by oblazej

2021-04-23 19:56 UTC, bonsoirq requested changes
Review skończone, jest parę rzeczy nad którymi można się zastanowić, ale ogólnie bardzo spoko :) Idziemy w dobrym kierunku :D

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +        this.shapeControllers = ['circle', 'square', 'triangle', 'x'],
Czy ten nieużywany kod jest potrzebny 🤔?

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +          ctx.arc(50, 50, 45, 0, 2 * Math.PI);
Co jeśli wymiary canvasa ulegną nagłej zmianie, czy te wartości możemy jakoś od nich uzależnić? Wydaje mi się, że dałoby się to jakoś wyliczyć proporcjonalnie względem rozmiaru canvas 😁

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +      this.previewCanvas.clearRect(0, 0, 100, 100);
Ten fragment powtarza nam się w każdej metodzie, być może powinien być częścią metody `drawShape`, jak uważasz? Tutaj podobnie myślę że fajnie by było nie używać wartości wpisanych na stałe w przypadku gdybyśmy chcieli zmienić rozmiar canvasa 😝 Ogólnie raczej powinno się unikać wpisywania takich stałych pozbawionych kontekstu, ma to nawet swoją nazwę – `magic numbers` 🪄 https://en.wikipedia.org/wiki/Magic_number_%28programming%29

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +    initControllers(className, event) {
`Controllers` to dość niejednoznaczna nazwa która może wprowadzać w błąd, może lepszą by było coś w rodzaju `initButtonsClick` 🖱?

update: Sądzę że ten argument który nazywa się `event` w rzeczywistości powinien nazywać się `callback` zgodnie z javascriptową konwencją, a być może nawet bardziej verbose byłoby `clickHandler` 🧐

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +      }
Tutaj chyba niepotrzebnie piszemy całą pętlę `for` i w każdym jej przejściu wyciągamy za każdym razem wszystkie elementy po klasie. Proponuję coś takiego:

```js
const classElements = document.getElementsByClassName(className);
classElements.forEach(element => {
  element.addEventListener('click', (e) => callback(e.target.dataset.value));
});
```

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +      // this.colorControllers = getCollToObject(`p${this.id}-color`, this.colorControllers);
To chyba też możemy usunąć ;)

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +  // }
I tu podobnie, raczej nie potrzebujemy?

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
>  });
Brakuje trailing newline 🔚 Wyjaśnienie: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +    drawShape(ctx) {
Czy przekazywanie `ctx` jest potrzebne jeśli obiekt trzyma go w `this.previewCanvas`?

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +        this.color = color,
Zdaje się, że to chyba nawet błąd składni języka z kończeniem wyrażenia przecinkiem, i to wcięcie w kolejnych liniach po `id` zdaje się być niepotrzebne 🎬

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/index.html
> +                <div class="col p1-color blue" data-value="#1761eb"></div>
Zgaduję, że <div> łatwiej się styluje 😝 Ale z tego co widzę to mają być przyciski, zatem raczej powinny zostać użyte elementy <buttton>, warto przykładać uwagę do używanych znaczników, gdyż ich poprawny wybór ułatwia osobom z niepełnospranościami korzystanie ze stron z użyciem ułatwień dostępu ✨ https://www.lifewire.com/why-use-semantic-html-3468271

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/css/main.css
> +  border-top: 1px dotted;
Przy klikalnych elementach rozważyłbym jeszcze `cursor: pointer`, a w elementach które są obok siebie żeby sąsiednie nie miały podwójnego bordera można robić border tylko z lewej, a z użyciem `:last-child` dodać też z prawej do ostatniego elementu w rzędzie 💪 https://developer.mozilla.org/pl/docs/Web/CSS/:last-child

2021-04-23 19:56 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +    layoutColorChange = (bgCol, fgCol, fgFont) => {
Tu się przyczepię trochę na wyrost :D Ale ktoś czytający to w przyszłości nie będzie w stanie wywnioskować znaczenia nazw tych parametrów zbyt łatwo, gdy widzę `col` jednocześnie do głowy przychodzą mi `color` i `column` 🤯

2021-04-24 17:41 UTC, oblazej commented on tic-tac-toe/js/main.js
> +        this.shapeControllers = ['circle', 'square', 'triangle', 'x'],
Teraz już nie 😳

2021-04-24 17:44 UTC, oblazej commented on tic-tac-toe/js/main.js
> +          ctx.arc(50, 50, 45, 0, 2 * Math.PI);
Zamierzam rozwinąć tę funkcję w dalszym etapie i uczynić ją bardziej uniwersalną (poza ustawieniami gracza, będzie również rysować kształty w trakcie rozgrywki w odpowiednich miejscach)

2021-04-24 17:52 UTC, oblazej commented on tic-tac-toe/js/main.js
> +      this.previewCanvas.clearRect(0, 0, 100, 100);
Ten fragment powtarza się, ponieważ w trakcie rozgrywki również chcę używać `drawShape`, nie oczyszczając uprzednio canvasa 😅 Stałe wartości zredukuję w dalszej pracy nad kodem 😌

2021-04-24 17:59 UTC, oblazej commented on tic-tac-toe/js/main.js
> +    drawShape(ctx) {
Jak wspominałem wcześniej - kontekst zmieni się po rozpoczęciu rozgrywki, dlatego jest przekazywany jako parametr.

2021-04-24 18:19 UTC, bonsoirq commented on tic-tac-toe/js/main.js
> +    drawShape(ctx) {
Wówczas można pozbyć się tego argumentu i przypisać nowy kontekst do `this.previewCanvas`, przy okazji chyba przemianowując go na `this.ctx`, jak myślisz?

2021-04-24 21:57 UTC, oblazej commented on tic-tac-toe/js/main.js
> +    drawShape(ctx) {
Zgadza się 😅

2021-05-17 12:08 UTC, merged